environments:
  Dev 3 Umgebung:
    login_url: https://dev-3.ecki.ai/login
    password: h5KilB94-wS#X74FsW
    url: https://dev-3.ecki.ai/
    username: ext.may.gregor@europaparkde.onmicrosoft.com
  Dev2:
    login_url: https://dev-2.ecki.ai/login
    password: h5KilB94-wS#X74FsW
    url: https://dev-2.ecki.ai/
    username: ext.may.gregor@europaparkde.onmicrosoft.com
