{{- $ctx := dict "found" false }}
{{- range $name, $config := .Values }}
{{- if eq (include "ui-testing-tool.isImageUpdated" (dict "config" $config)) "true" }}
{{- $_ := set $ctx "found" true }}
{{- end }}
{{- end }}
{{- if index $ctx "found" }}
apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: {{ .Release.Name }}
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: {{ .Release.Name | quote }}
      images:
        {{- range $name, $config := .Values }}
        {{- if eq (include "ui-testing-tool.isImageUpdated" (dict "config" $config)) "true" }}
        - alias: {{ $name }}
          imageName: "{{ index $config "image" "repository" }}:{{ index $config "image" "tag" }}"
          commonUpdateSettings:
            updateStrategy: digest
          manifestTargets:
            helm:
              name: "{{ $name }}.image.repository"
              tag: "{{ $name }}.image.tag"
        {{- end }}
        {{- end }}
{{- end }}
