apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ui-testing-tool.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: http
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ui-testing-tool
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: {{ .Release.Name }}-transport
  labels:
    {{- include "ui-testing-tool.labels" . | nindent 4 }}
spec:
  forwardingTimeouts:
    responseHeaderTimeout: "120s"
    idleConnTimeout: "120s"
