environment: production

domain: ui-testing-tool.data.mayflower.tech

images:
  app:
    image: ghcr.io/mayflower/ui-testing-tool/ui-testing-tool
    tag: latest # managed by argocd-image-updater

config:
  FLASK_ENV: "production"
